### PR TITLE
Switch to the HA gpg pool and always install https apt pkg

### PR DESCRIPTION
**Pull request by tas50**
Get things passing again

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
It's HA, so it must be better.

**Comment by chasebolt** [comment]
after some testing, sks is just unstable and fails a high percentage of the time (we also switched from sks to mit in a previous commit).

keyserver.ubuntu.com seems to be the most stable in my testing.

**Comment by rmoriz** [comment]
Are you sure this solves the problem? I guess the connectivity issues are caused by rate limiting of the keyservers and the high volume of key requests due to https://github.com/chef/chef/issues/6294#issuecomment-318696197 on chef-12

**Comment by stevendanna** [comment]
@rmoriz Yes, I think we came to the same conclusion but failed to follow up here: That the real issue is that apt_repository isn't properly idempotent so it causes many more requests than it needs to.

**Pull request closed without merging**
